version: '3'
services:

  discord:
    image: azuki774/mawinter-discord:develop
    container_name: mawinter-discord
    restart: always
    env_file:
    - token.env
    environment:
    - RUNENV=local
    - TZ=Asia/Tokyo
    - MAWINTER_PATH=mawinter-server
    - USE_MOCK=1 # 0 .. Use local server, 1 .. use internal mock

