version: '3'
services:

  discord:
    image: azuki774/mawinter-discord:develop
    container_name: mawinter-discord
    restart: always
    env_file:
    - token.env
    environment:
    - RUNENV=local
    - TZ=Asia/Tokyo
    - USE_MOCK=0 # 0 .. Use local server, 1 .. use internal mock

  maw-db:
    image: mariadb:10.7.3
    restart: always
    container_name: mawinter-db
    command:
        - mysqld
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
    ports:
        - "3306:3306"
    environment:
        - MYSQL_DATABASE=mawinter
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pwd
        - TZ=Asia/Tokyo
    volumes:
        - ../../build/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  maw-api:
    image: ghcr.io/azuki774/mawinter-api:latest
    container_name: mawinter-api
    ports:
        - "8080:80"
    environment: 
        - MYSQL_DATABASE=mawinter
        - BASIC_AUTH_USERNAME=test
        - BASIC_AUTH_PASSWORD=test
        - DB_WAITTIME=20
