version: '3'
services:

  discord:
    image: azuki774/mawinter-discord:develop
    container_name: mawinter-discord
    restart: always
    env_file:
    - token.env
    environment:
    - RUNENV=local
    
