apiVersion: apps/v1
kind: Deployment
metadata:
  name: mawinter-discord
spec:
  selector:
    matchLabels:
      app: mawinter-discord
  template:
    metadata:
      labels:
        app: mawinter-discord
    spec:
      resource:
      containers:
      - name: mawinter-discord
        image: ghcr.io/azuki774/mawinter-discord:develop
        imagePullPolicy: Always
        env:
        - name: RUNENV
          value: development
        - name: TZ
          value: Asia/Tokyo
        - name: USE_MOCK
          value: "0"
        - name: USER_MAWINTER_PATH
          value: https://k8s-dev.azuki-black.tech/mawinter/
        - name: USER_DISCORD_ID
          value: "288297568369246208"
        - name: USER_DISCORD_NAME
          value: azuki
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: maw-discord-dev-secret
              key: AUTH_TOKEN
        - name: USER_MAWINTER_USER
          valueFrom:
            secretKeyRef:
              name: maw-basic-auth
              key: username
        - name: USER_MAWINTER_PASS
          valueFrom:
            secretKeyRef:
              name: maw-basic-auth
              key: password
